src/blog/urls.py
from django.urls import path
from .views import blog_list_view, post_detail_view, post_create_view


urlpatterns = [
    path("", blog_list_view, name="blog-list"),
    path("create/", post_create_view, name="post-create"),
    path('<slug:slug>/', post_detail_view, name='post-detail'),
    # path('<slug:slug>/update', post_update_view, name='tour-detail'),
]

src/chargik/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from tours.views import home_view, contacts_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home_view, name="home"),
    path("contacts", contacts_view, name="contacts"),
    path('accounts/', include('allauth.urls')),
    path('tours/', include('tours.urls')),
    path('blog/', include('blog.urls')),
    path('reviews/', include('reviews.urls')),
    path('agency/', include('agencies.urls')),
    path('hotels/', include('hotels.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/tours/urls.py
from django.urls import path
from .views import tour_list_view, tour_detail_view, tour_corporate_view, tour_create_view, create_day_description_form, create_date_price_form


urlpatterns = [
    path("", tour_list_view, name="tour-list"),
    path("create/", tour_create_view, name="tour-create"),
    path("htmx/create-day-description", create_day_description_form, name="tour-create-day-form"),
    path("htmx/create-date-price", create_date_price_form, name="tour-create-date-price-form"),
    path("corporate/", tour_corporate_view, name="tour-corporate"),
    path('<slug:slug>/', tour_detail_view, name='tour-detail'),
]

src/tours/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.contenttypes.fields import GenericRelation

from ckeditor_uploader.fields import RichTextUploadingField
from django_resized import ResizedImageField

from reviews.models import Review
from hotels.models import Hotel

# Create your models here.


def tours_img_upload(instance, filename):
    return f"tours/{instance.slug}/attachments/{filename}"

class Tour(models.Model):
    USD = "$"
    EUR = "€"
    BYN = "BYN"
    RUB = "₽"
    CURRENCY_CHOICES = [
        (USD, "$"),
        (EUR, "€"),
        (BYN, "BYN"),
        (RUB, "₽"),
    ]

    active = models.BooleanField(default=False, verbose_name='Отображать')
    title = models.CharField(max_length=128, verbose_name='Название тура')
    slug = models.SlugField(unique=True, verbose_name='Ссылка на тур')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.DO_NOTHING)

    seo_keywords = models.TextField(null=True, blank=True, verbose_name="SEO слова")
    seo_description = models.TextField(null=True, blank=True, verbose_name="SEO описание")

    img = ResizedImageField(upload_to=tours_img_upload)
    first_title = models.TextField(null=True, blank=True, verbose_name="Заголовок на изображении")
    second_title = models.TextField(null=True, blank=True, verbose_name="краткое описание")

    price = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True, verbose_name="Цена")
    old_price = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True, verbose_name="Старая цена")
    currency = models.CharField(max_length=10, default=BYN, choices=CURRENCY_CHOICES, verbose_name="валюта")
    service_price = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True, default=0, verbose_name="Туруслуга взрослый")
    service_price_child = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True, default=0, verbose_name="Туруслуга детский")
    comission = models.FloatField(null=True, blank=True, default=10, verbose_name="Комиссия")

    route = models.TextField(null=True, blank=True, verbose_name="Маршрут")
    country = models.ManyToManyField('CountryTour')
    num_days = models.IntegerField(default=1, verbose_name="Количество дней")
    night_transfer = models.IntegerField(default=0, verbose_name="Ночных перездов")
    description_tour = models.TextField(null=True, blank=True, verbose_name="описание тура")

    included = models.TextField(null=True, blank=True, verbose_name="Включено в стоимость")
    not_included = models.TextField(null=True, blank=True, verbose_name="Дополнительно оплачивается")

    hotels = models.ManyToManyField(Hotel, verbose_name="Отели")
    category = models.ManyToManyField('CategoryTour', verbose_name="тип тура")
    reviews = GenericRelation(Review, related_query_name="tour")
    # manager = models.ManyToManyField(Manager, default=None, verbose_name="Менеджер")

    count_views = models.PositiveIntegerField(default=0)

    timestamp = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True, null=True)


    def __str__(self):
        return f'{self.title}'

    @property
    def days_description(self):
        qs = TourDescriptionDay.objects.filter(tour_id=self.pk, active=True)
        return qs

    @property
    def day_quota(self):
        qs = TourDayQuota.objects.filter(tour_id=self.pk, active=True)
        return qs

    def get_absolute_url(self):
        return reverse('tour-detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Тур'
        verbose_name_plural = 'Туры'
        ordering = ["-timestamp", "-updated"]


class TourDescriptionDay(models.Model):
    tour = models.ForeignKey(Tour, default=None, on_delete=models.CASCADE, verbose_name="Тур")
    active = models.BooleanField(default=False)
    day = models.CharField(default="День 1", max_length=12)
    description = RichTextUploadingField(null=True, blank=True)

    def __str__(self):
        return f"Тур {self.tour} - {self.day}"

    class Meta:
        verbose_name = 'Описание дня'
        verbose_name_plural = 'Описание дней'


class TourDayQuota(models.Model):
    tour = models.ForeignKey(Tour, default=None, on_delete=models.CASCADE)
    active = models.BooleanField(default=False, verbose_name="Активная дата")
    tour_date = models.DateField(null=True, verbose_name="Дата тура")
    total_quotas = models.PositiveIntegerField(null=True, blank=True, verbose_name="Всего мест")
    # active_quotas = models.PositiveIntegerField(verbose_name="Оставшиеся места")
    sold_quotas = models.PositiveIntegerField(null=True, blank=True, verbose_name="Проданные места")
    price_adult = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена взрослый")
    price_child = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена детский")

    def __str__(self):
        return f'{self.tour} - {self.tour_date}'

    class Meta:
        verbose_name = 'Дата-Квота'
        verbose_name_plural = 'Даты-Квоты'
        ordering = ["tour_date"]


class CategoryTour(models.Model):
    title = models.CharField(max_length=128, default="")
    slug = models.SlugField(unique=True)
    img = ResizedImageField(upload_to="tours/categoty", null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        return reverse('category', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Тип тура'
        verbose_name_plural = 'Типы туров'
        ordering = ["title"]


class CountryTour(models.Model):
    title = models.CharField(max_length=128, default="")
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        return reverse('country', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Страна'
        verbose_name_plural = 'Страны'
        ordering = ["title"]

src/tours/forms.py
from django import forms
from django.forms import inlineformset_factory, modelformset_factory
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from tours.models import Tour, TourDayQuota, TourDescriptionDay


input_css_class = "form-control"

class TourForm(forms.ModelForm):
    class Meta:
        model = Tour
        exclude = ["user", "count_views"]
        # fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['name'].widget.attrs['placeholder'] = "Your name"
        for field in self.fields:
            if field in ['active']:
                continue
            self.fields[field].widget.attrs['class'] = input_css_class


class TourUpdateForm(forms.ModelForm):
    class Meta:
        model = Tour
        exclude = ["user", "count_views"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['name'].widget.attrs['placeholder'] = "Your name"
        for field in self.fields:
            if field in ['active']:
                continue
            self.fields[field].widget.attrs['class'] = input_css_class


class TourDescriptionDayForm(forms.ModelForm):
    base_textarea_id = "id_day_description"

    class Meta:
        model = TourDescriptionDay
        exclude = ["tour"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['name'].widget.attrs['placeholder'] = "Your name"
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = input_css_class

TourDescriptionDayModelFormSet = modelformset_factory(
    TourDescriptionDay,
    form=TourDescriptionDayForm,
    exclude=["tour"],
    extra=0,
    can_delete=True
)

TourDescriptionDayInlineFormSet = inlineformset_factory(
    Tour,
    TourDescriptionDay,
    form=TourDescriptionDayForm,
    formset=TourDescriptionDayModelFormSet,
    exclude=["tour"],
    extra=0,
    can_delete=True
)


class TourDayQuotaForm(forms.ModelForm):
    class Meta:
        model = TourDayQuota
        exclude = ["tour"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['name'].widget.attrs['placeholder'] = "Your name"
        for field in self.fields:
            if field in ['active']:
                continue
            self.fields[field].widget.attrs['class'] = input_css_class

TourDayQuotaModelFormSet = modelformset_factory(
    TourDayQuota,
    form=TourDayQuotaForm,
    exclude=["tour"],
    extra=0,
    can_delete=True
)

TourDayQuotaInlineFormSet = inlineformset_factory(
    Tour,
    TourDayQuota,
    form=TourDayQuotaForm,
    formset=TourDayQuotaModelFormSet,
    exclude=["tour"],
    extra=0,
    can_delete=True
)

src/tours/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.db.models import Avg, Count
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404


from .models import Tour, TourDescriptionDay, TourDayQuota
from .forms import TourForm, TourDescriptionDayForm, TourDayQuotaForm

from blog.models import Post
from callback.forms import CallBackForm
# Create your views here.


@staff_member_required
def create_day_description_form(request):
    form_day = TourDescriptionDayForm(request.POST or None, request.FILES or None)
    context = {
        'form_day': form_day
    }
    return render(request, 'forms/create_day_form.html', context)


@staff_member_required
def create_date_price_form(request):
    form_qouta = TourDayQuotaForm(request.POST or None)
    context = {
        'form_qouta': form_qouta
    }
    return render(request, 'forms/create_date_price_form.html', context)


@staff_member_required
def tour_create_view(request):
    context = {}
    form = TourForm(request.POST or None, request.FILES or None)
    form_day = TourDescriptionDayForm(request.POST or None, request.FILES or None)
    form_qouta = TourDayQuotaForm(request.POST or None)
    if form.is_valid() and form_day.is_valid() and form_qouta.is_valid():
        tour = form.save(commit=False)
        tour.user = request.user
        tour.save()
        tour_day = form_day.save(commit=False)
        tour_day.tour = tour
        tour_day.save()
        tour_quota = form_qouta.save(commit=False)
        tour_quota.tour = tour
        form_qouta.save()
        return redirect('tour-detail', slug=tour.slug)
    print(form.errors, form_day.errors)
    context['form'] = form
    context['form_day'] = form_day
    context['form_qouta'] = form_qouta
    return render(request, 'tours/create.html', context)


@staff_member_required
def tour_update_view(request, slug=None):
    tour = get_object_or_404(Tour, slug=slug)
    tour_day_descriptions = TourDescriptionDay.objects.filter(tour=tour)
    tour_day_qoutas = TourDayQuota.objects.filter(tour=tour)
    context = {"object": tour}
    form = TourForm(request.POST or None, request.FILES or None, instance=tour)
    form_day = TourDescriptionDayForm(request.POST or None, request.FILES or None, queryset=tour_day_descriptions)
    form_qouta = TourDayQuotaForm(request.POST or None, queryset=tour_day_qoutas)
    return render(request, 'tours/update.html', context)



def tour_list_view(request):
    tours = Tour.objects.annotate(Count("reviews"), Avg("reviews__rating", default=0))
    context = {
        "objects" : tours
    }
    return render(request, "tours/list-tours.html", context)


def tour_detail_view(request, slug=None):
    tour = get_object_or_404(Tour, slug=slug)
    # object_description_day = TourDescriptionDay.objects.filter(tour=object)
    reviews = tour.reviews.filter(active=True).aggregate(Count("id"), Avg("rating", default=0))
    # count_review, avg_rating = tour.reviews.aggregate(Count("id"), Avg("rating", default=0))
    form = CallBackForm(request.POST or None)
    if form.is_valid():
        callback = form.save(commit=False)
        callback.url = request.get_full_path()
        callback.save()

    context = {
        "object" : tour,
        "form": form,
        "reviews": reviews,
        # "count_review": count_review,
        # "avg_rating": avg_rating,
    }
    return render(request, "tours/detail.html", context)


def tour_corporate_view(request):
    tours = Tour.objects.annotate(Count("reviews"), Avg("reviews__rating", default=0)).filter(active=True)[:6]
    form = CallBackForm(request.POST or None)
    if form.is_valid():
        callback = form.save(commit=False)
        callback.url = request.get_full_path()
        callback.save()
        form.send_email(name=callback.name, phone=callback.phone_number, url=callback.url)
        return HttpResponse('<div class="flex items-center p-4 mb-4 text-sm text-green-800 border border-green-300 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400 dark:border-green-800" role="alert"><svg class="flex-shrink-0 inline w-4 h-4 mr-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20"><path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/></svg><span class="sr-only">Info</span><div><span class="font-medium">Success alert!</span> Change a few things up and try submitting again.</div></div>')

    context = {
        "objects" : tours,
        "form": form
    }
    return render(request, "tours/corporate.html", context)


def home_view(request):
    tours = Tour.objects.annotate(Count("reviews"), Avg("reviews__rating", default=0)).order_by("-updated")[:6]
    posts = Post.objects.annotate(Count("reviews"), Avg("reviews__rating", default=0)).order_by("-updated")[:6]
    context = {
        "tours": tours,
        "posts": posts,
    }

    return render(request, "home.html", context)

def contacts_view(request):
    context = {

    }
    return render(request, "contacts.html", context)

src/templates/tours/create.html
{% extends "base.html" %}

{% block content %}

<form method="POST" action="." enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  {{ form_day.media }}
  {{ form_day.as_p }}
  {{ form_qouta.as_p }}
  <div class="flex mt-4 md:mt-0 md:ml-4">
    <button type="button" hx-get="{% url 'tour-create-day-form' %}" hx-target="#day_forms" hx-swap="beforeend"
        class="inline-flex items-center px-4 py-2 ml-3 text-sm font-medium text-white bg-indigo-600 border border-transparent rounded-md shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
        Добавить день
    </button>
  </div>

  <div class="flex mt-4 md:mt-0 md:ml-4">

  </div>
  <button type="submit" class="mt-2 btn-submit">Создать</button>
</form>

{% endblock %}

src/templates/tours/detail-tailwind.html
{% extends "base.html" %}

{% block head_title %}{{ object.title }}{% endblock head_title %}


{% block content %}

<div class="relative md:w-1/2 sm:w-max">
    <img class="rounded-lg" src="{{ object.img.url }}" alt="{{ object.title }}">

    <div class="flex flex-row justify-between pt-2">
        <div>
            <h1 class="text-xl font-bold">{{ object.title }}</h1>
        </div>
        <div>
            <h1 class="text-xl font-bold">{{ object.price }}{{ object.currency }}</h1>
        </div>
    </div>
    <div class="flex py-2">
        <p>{{ object.second_title }}</p>
    </div>

    <div class="flex items-center">
        <svg class="w-4 h-4 mr-1 text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
            <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
        </svg>
        <p class="ml-2 text-sm font-bold text-gray-900 dark:text-white">4.95</p>
        <span class="w-1 h-1 mx-1.5 bg-gray-500 rounded-full dark:bg-gray-400"></span>
        <a href="#" class="text-sm font-medium text-gray-900 underline hover:no-underline dark:text-white">73 reviews</a>
    </div>

    <hr class="w-auto h-1 mx-auto my-4 bg-gray-100 border-0 rounded md:my-10 dark:bg-gray-700">
    <div class="space-y-2">
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">О туре</h5>
        <p class="font-normal text-gray-700 dark:text-gray-400">{{ object.description_tour }}</p>

        <div class="flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15 10.5a3 3 0 11-6 0 3 3 0 016 0z" />
                <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 10.5c0 7.142-7.5 11.25-7.5 11.25S4.5 17.642 4.5 10.5a7.5 7.5 0 1115 0z" />
            </svg>
            <p class="font-normal text-gray-700 dark:text-gray-400">{{ object.route }}</p>
        </div>
        <div class="flex flex-row items-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <p class="font-normal text-gray-700 dark:text-gray-400">{{ object.num_days }} дня</p>
        </div>
    </div>
    <hr class="w-auto h-1 mx-auto my-4 bg-gray-100 border-0 rounded md:my-10 dark:bg-gray-700">
    <div class="pt-2 space-y-2">
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Программа тура</h5>
        {% for day in object.tourdescriptionday_set.all %}
            <p class="text-xl font-bold tracking-tight text-gray-900 dark:text-white">{{ day.day }}</p>
            {{ day.description|safe }}
        {% endfor %}
    </div>
    <hr class="w-auto h-1 mx-auto my-4 bg-gray-100 border-0 rounded md:my-10 dark:bg-gray-700">
    <div class="pt-2 space-y-2">
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Входит в стомость:</h5>
        <p class="font-normal text-gray-700 dark:text-gray-400">{{ object.included|safe }}</p>
    </div>
    <div class="pt-2 space-y-2">
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Дополнительно оплачивается:</h5>
        <p class="font-normal text-gray-700 dark:text-gray-400">{{ object.not_included|safe }}</p>
    </div>
    <hr class="w-auto h-1 mx-auto my-4 bg-gray-100 border-0 rounded md:my-10 dark:bg-gray-700">

    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Даты тура:</h5>
    {% for tdq in object.tourdayquota_set.all %}
        <div class="w-auto p-6 my-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700 hover:shadow-gray-500">
            <div class="flex flex-row">
                <div class="basis-1/4">
                    <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">{{ tdq.tour_date|date:"d.m.Y" }}</p>
                </div>

                <div class="basis-1/2">
                    <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">Осталось мест на эту дату: {{ tdq.total_quotas }}</p>
                </div>

            </div>
            <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">Стоимость тура для взрослого: {{ tdq.price_adult }}{{ object.currency }}</p>
            <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">Стоимость тура для ребенка: {{ tdq.price_child }}{{ object.currency }}</p>
            <a href="#" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                Забронировать
                <svg class="w-3.5 h-3.5 ml-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
                </svg>
            </a>
        </div>
    {% endfor %}

    <div class="pb-20"></div>
</div>
{% endblock content %}

src/templates/tours/list-card.html
<div class="col-md-6 col-xl-4">
    <div class="card card-hover-shadow pb-0 h-100">
        <!-- Overlay item -->
        <div class="position-relative">
            <!-- Image -->
            <img class="card-img-top" src="{{ object.img.url }}" alt="" />
            <!-- Overlay -->
            <div class="card-img-overlay d-flex flex-column p-4 z-index-1">
                <!-- Card overlay top -->
                <div>
                    <span class="badge text-bg-danger">30% Off</span>
                    <span class="badge text-bg-dark">Adventure</span>
                </div>
                <!-- Card overlay bottom -->
                <div class="w-100 mt-auto">
                    <span class="badge text-bg-white fs-6">Дней: {{ object.num_days }}</span>
                </div>
            </div>
        </div>
        <!-- Image -->

        <!-- Card body START -->
        <div class="card-body px-3">
            <!-- Title -->
            <h5 class="card-title mb-0"><a href="{{ object.get_absolute_url }}" class="stretched-link">{{ object.title }}</a></h5>
            <span class="small"><i class="far fa-calendar-alt me-2"></i>April 12-17</span>

            <!-- List -->
            <ul class="nav nav-divider mt-3 mb-0">
                <li class="nav-item h6 fw-normal mb-0">
                    <i class="fa-solid fa-star text-orange me-2"></i>{{ object.reviews__rating__avg }}
                </li>
                <li class="nav-item h6 fw-normal mb-0">
                    Отзывов: {{ object.reviews__count }}
                </li>
            </ul>
        </div>
        <!-- Card body END -->

        <!-- Card footer START-->
        <div class="card-footer pt-0">
            <!-- Price and Button -->
            <div class="d-sm-flex justify-content-sm-between align-items-center flex-wrap">
                <!-- Price -->
                <div class="hstack gap-2">
                    <h5 class="fw-normal text-success mb-0">{{ object.price }}{{ object.currency }}</h5>
                    <small>/за человека</small>
                    <span class="text-decoration-line-through">{{ object.old_price }}{{ object.currency }}</span>
                </div>
                <!-- Button -->
                <div class="mt-2 mt-sm-0">
                    <a href="#" class="btn btn-sm btn-primary mb-0">Подробнее</a>
                </div>
            </div>
        </div>

    </div>
</div>
<!-- Card item END -->